plantatree/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include

urlpatterns = [
    url(r'^', include(('store.urls', 'store'), namespace="store")),
    url(r'^admin/', admin.site.urls),
]

store/urls.py
from django.urls import path

from store.views import index, login, cart, tree, product, wishlist, search, \
    checkout, search, all, register
from store.views.cart import TYPE_TREE, TYPE_PRODUCT

urlpatterns = [
    path('', index.index_view, name='index'),
    path('login/', login.login_view, name='login'),
    path('addtreetocart/<int:item_id>/<int:qty>/', cart.add,
         {'type_of': TYPE_TREE}, name='addtreetocart'),
    path('addproducttocart/<int:item_id>/<int:qty>/', cart.add,
         {'type_of': TYPE_PRODUCT}, name='addproducttocart'),
    path('cart/', cart.cart, name='cart'),
    path('carttreeadd/<int:item_id>/', cart.increase_tree_qty,
         name='increase_tree_qty'),
    path('carttreeremove/<int:item_id>/', cart.decrease_tree_qty,
         name='decrease_tree_qty'),
    path('carttreedelete/<int:item_id>/', cart.remove_tree,
         name='remove_tree'),
    path('cartproductadd/<int:item_id>/', cart.increase_product_qty,
         name='increase_product_qty'),
    path('cartproductremove/<int:item_id>/', cart.decrease_product_qty,
         name='decrease_product_qty'),
    path('cartproductdelete/<int:item_id>/', cart.remove_product,
         name='remove_product'),
    path('tree/<int:item_id>/', tree.get_tree,
         name="get_tree"),
    path('product/<int:item_id>/', product.get_product,
         name="get_product"),
    path('addtreetowishlist/<int:item_id>/', wishlist.add,
         {'type_of': TYPE_TREE}, name='addtreetowishlist'),
    path('addproducttowishlist/<int:item_id>/', wishlist.add,
         {'type_of': TYPE_PRODUCT}, name='addproducttowishlist'),
    path('wishlist/', wishlist.wishlist, name='wishlist'),
    path('wishlistproductremove/<int:item_id>/', wishlist.remove_product,
         name='removeproductfromwishlist'),
    path('wishlisttreeremove/<int:item_id>/', wishlist.remove_tree,
         name='removetreefromwishlist'),
    path('register/', register.register_view, name='register'),
    path('search/', search.get_item, name='search'),
    path('all/', all.show_all,
         name='showall'),
    path('all/trees/', all.show_trees,
         name='showalltrees'),
    path('all/products/', all.show_products,
         name='showallproducts'),
    path('checkout/', checkout.checkout, name='checkout'),
    path('checkout/process/', checkout.process_checkout, name='process'),
]

store/models.py
import django.contrib.auth
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=10000)

    def __str__(self):
        return self.name


class Tree(models.Model):
    HIGH_MAINT = 'HG'
    MEDIUM_MAINT = 'MD'
    LOW_MAINT = 'LW'
    MAINTENANCE_CHOICES = (
        (HIGH_MAINT, 'High Maintenance'),
        (LOW_MAINT, 'Low Maintenance'),
        (MEDIUM_MAINT, 'Medium Maintenance'),
    )
    FAST_RATE = 'FR'
    MEDIUM_RATE = 'LR'
    SLOW_RATE = 'SR'
    GROWTH_RATE_CHOICES = (
        (FAST_RATE, 'Fast Growth'),
        (MEDIUM_RATE, 'Medium Growth'),
        (SLOW_RATE, 'Slow Growth'),
    )
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=10000)
    fun_facts = models.CharField(max_length=500)
    price = models.FloatField()
    category = models.ForeignKey('Category', on_delete=models.PROTECT,
                                 related_name='trees')
    maintenance = models.CharField(choices=MAINTENANCE_CHOICES, max_length=2)
    height = models.FloatField()
    growth_rate = models.CharField(choices=GROWTH_RATE_CHOICES, max_length=2)
    year_one = models.CharField(max_length=100000)
    year_two = models.CharField(max_length=100000)
    year_three = models.CharField(max_length=100000)
    year_five = models.CharField(max_length=100000)
    year_ten = models.CharField(max_length=100000)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=10000)
    price = models.FloatField()
    category = models.ForeignKey('Category', on_delete=models.PROTECT,
                                 related_name='products')
    image = models.CharField(max_length=100000)

    def __str__(self):
        return self.name


# a little bit of copying is better than a little bit of abstraction
# also... I'm lazy

class Wishlist(models.Model):
    user = models.ForeignKey(django.contrib.auth.get_user_model(),
                             related_name='wishlist', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class WishlistTreeItem(models.Model):
    wishlist = models.ForeignKey('Wishlist', on_delete=models.CASCADE,
                                 related_name='trees')
    tree = models.ForeignKey('Tree', on_delete=models.CASCADE)

    def __str__(self):
        return self.wishlist.user.username + " " + self.tree.name


class WishlistProductItem(models.Model):
    wishlist = models.ForeignKey('Wishlist', on_delete=models.CASCADE,
                                 related_name='products')
    product = models.ForeignKey('Product', on_delete=models.CASCADE)

    def __str__(self):
        return self.wishlist.user.username + " " + self.product.name


class Cart(models.Model):
    user = models.ForeignKey(django.contrib.auth.get_user_model(),
                             related_name='cart', on_delete=models.CASCADE)

    @property
    def total_cost(self):
        total = 0

        for tree in self.trees.all():
            total += tree.total_cost

        for product in self.products.all():
            total += product.total_cost

        return total

    @property
    def item_count(self):
        total = 0

        for tree in self.trees.all():
            total += tree.qty

        for product in self.products.all():
            total += product.qty

        return total

    def __str__(self):
        return self.user.username


class CartTreeItem(models.Model):
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE,
                             related_name='trees')
    tree = models.ForeignKey('Tree', on_delete=models.CASCADE)
    qty = models.IntegerField()

    @property
    def total_cost(self):
        return self.tree.price * self.qty

    def __str__(self):
        return self.cart.user.username + " " + self.tree.name


class CartProductItem(models.Model):
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE,
                             related_name='products')
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    qty = models.IntegerField()

    def __str__(self):
        return self.cart.user.username + " " + self.product.name

    @property
    def total_cost(self):
        return self.product.price * self.qty

store/views/all.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from store.models import Tree, Product


@require_http_methods(["GET"])
def show_all(request):
    trees = set()
    products = set()

    trees.update(Tree.objects.all())
    products.update(Product.objects.all())

    return render(request, 'all.html', context={
        'trees': trees,
        'products': products,
        'page_title': "All"
    })


def show_trees(request):
    trees = set()

    trees.update(Tree.objects.all())

    return render(request, 'all.html', context={
        'trees': trees,
        'page_title': "All Trees"
    })


def show_products(request):
    products = set()

    products.update(Product.objects.all())

    return render(request, 'all.html', context={
        'products': products,
        'page_title': "All Products"
    })

store/views/cart.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponseServerError, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods

from store.models import CartTreeItem, Cart, Tree, Product, CartProductItem

TYPE_TREE = 'tree'
TYPE_PRODUCT = 'product'


@login_required
@require_http_methods(["GET"])
@transaction.atomic
def add(request, type_of, item_id, qty):
    """"
    add: adds an item to the users cart

    NB: not currently a fan of this GET a specific URL implementation
    but it makes it easier to implement on the product page and
    speed is more important anyway.
    """
    try:
        cart = Cart.objects.get(user=request.user)
    except Cart.DoesNotExist:
        cart = Cart(user=request.user)
        cart.save()

    if type_of == TYPE_TREE:
        item = get_object_or_404(Tree, pk=item_id)

        # try and see if the item is already in the cart
        cart_item = CartTreeItem.objects.filter(tree=item, cart=cart).first()

        # otherwise create a new one
        if cart_item is None:
            cart_item = CartTreeItem(
                cart=cart,
                tree=item,
                qty=qty
            )
        else:
            cart_item.qty += qty

        cart_item.save()

        return render(request, 'addtocart.html', context={
            'image': item.year_one,
            'item_name': item.name,
            'item_qty': qty,
            'page_title': "Item Added To Cart"
        })

    elif type_of == TYPE_PRODUCT:
        item = get_object_or_404(Product, pk=item_id)

        cart_item = CartProductItem.objects.filter(product=item,
                                                   cart=cart).first()

        if cart_item is None:
            cart_item = CartProductItem(
                cart=cart,
                product=item,
                qty=qty
            )
        else:
            cart_item.qty += qty

        cart_item.save()

        return render(request, 'addtocart.html', context={
            'image': item.image,
            'item_name': item.name,
            'item_qty': qty,
            'page_title': "Item Added To Cart"
        })

    else:
        return HttpResponseServerError()


@login_required
@require_http_methods(["GET"])
def increase_tree_qty(request, item_id):
    item = get_object_or_404(CartTreeItem, pk=item_id)
    item.qty += 1
    item.save()
    return redirect('store:cart')


@login_required
@require_http_methods(["GET"])
def decrease_tree_qty(request, item_id):
    item = get_object_or_404(CartTreeItem, pk=item_id)
    item.qty += -1

    if item.qty < 1:
        item.delete()
    else:
        item.save()

    return redirect('store:cart')


@login_required
@require_http_methods(["GET"])
def remove_tree(request, item_id):
    item = get_object_or_404(CartTreeItem, pk=item_id)
    item.delete()
    return redirect('store:cart')


@login_required
@require_http_methods(["GET"])
def increase_product_qty(request, item_id):
    item = get_object_or_404(CartProductItem, pk=item_id)
    item.qty += 1
    item.save()
    return redirect('store:cart')


@login_required
@require_http_methods(["GET"])
def decrease_product_qty(request, item_id):
    item = get_object_or_404(CartProductItem, pk=item_id)
    item.qty += -1

    if item.qty < 1:
        item.delete()
    else:
        item.save()

    return redirect('store:cart')


@login_required
@require_http_methods(["GET"])
def remove_product(request, item_id):
    item = get_object_or_404(CartProductItem, pk=item_id)
    item.delete()
    return redirect('store:cart')


@login_required
@require_http_methods(["GET"])
def cart(request):
    try:
        cart_ob = Cart.objects.get(user=request.user)
    except Cart.DoesNotExist:
        cart_ob = Cart(user=request.user)
        cart_ob.save()

    return render(request, 'cart.html', context={
        'page_title': 'Cart',
        'trees': cart_ob.trees.all(),
        'products': cart_ob.products.all(),
    })

store/views/checkout.py
import requests
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from store.models import Cart


@login_required
def checkout(request):
    try:
        cart_ob = Cart.objects.get(user=request.user)
    except Cart.DoesNotExist:
        return redirect('store:cart')

    total_cost = cart_ob.total_cost

    free_shipping = False

    if cart_ob.item_count > 10:
        free_shipping = True
    else:
        total_cost += 35

    return render(request, 'checkout.html', context={
        'page_title': 'Checkout',
        'trees': cart_ob.trees.all(),
        'products': cart_ob.products.all(),
        'total': total_cost,
        'free_shipping': free_shipping
    })


@login_required
@csrf_exempt
def process_checkout(request):
    cart_ob = Cart.objects.get(user=request.user)

    message = "Dear {}\n\n".format(request.POST["first_name"])
    message += "Thank you for your order. It will be dispatched at the " \
               "first " \
               "possible instant. Please find your order details below.\n\n"

    message += "QTY - PRODUCT NAME - COST\n"

    for tree_item in cart_ob.trees.all():
        message += "{} - {} - {}\n".format(tree_item.qty, tree_item.tree.name,
                                           tree_item.total_cost)

    for product_item in cart_ob.products.all():
        message += "{} - {} - {}\n".format(product_item.qty,
                                           product_item.product.name,
                                           product_item.total_cost)

    total_cost = cart_ob.total_cost

    if cart_ob.item_count > 10:
        message += "1 - SHIPPING - FREE\n\n"
    else:
        total_cost += 35
        message += "1 - SHIPPING - $35\n\n"

    message += "Total Cost: {}\n\n".format(total_cost)

    message += "Thanks\nJim"

    response = requests.post(
        "https://api.mailgun.net/v3/plantatree.xyz/messages",
        auth=("api", settings.MAILGUN_API_KEY),
        data={"from": "Jim Irrumabo <order@plantatree.xyz>",
              "to": [request.POST["email"]],
              "subject": "Thanks for ordering from Plant A Tree",
              "text": message})

    cart_ob.products.all().delete()
    cart_ob.trees.all().delete()

    return render(request, 'checkout_success.html')

store/views/login.py
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.shortcuts import render, redirect

from store.forms import LoginForm


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request=request, user=user)

                try:
                    next = request.GET["next"]
                except KeyError:
                    return redirect('store:index')

                return redirect(next)

            else:
                messages.error(request, 'Incorrect Username or Password!')
                return redirect('store:login')
        else:
            messages.error(request, 'Incorrect Username or Password!')
            return redirect('store:login')

    elif request.method == 'GET':
        form = LoginForm()

        return render(request, 'login.html', context={
            'form': form,
            'page_title': "Login",
        })

store/views/product.py
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_http_methods

from store.models import Product


@require_http_methods(["GET"])
def get_product(request, item_id):
    item = get_object_or_404(Product, pk=item_id)
    return render(request, 'product.html', context={
        'product': item,
        'page_title': item.name,
    })

store/views/register.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from store.forms import RegisterForm


def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            passwordV = form.cleaned_data['passwordV']

            is_user = User.objects.filter(username=username).exists()
            if is_user:
                messages.error(request, 'User already exists!')
                return redirect('store:register')

            else:
                if password == passwordV:
                    user = User.objects.create_user(username=username,
                                                    password=password)
                    user.save()
                    login(request=request, user=user)

                    return redirect('store:index')

                else:
                    messages.error(request, 'Passwords do not match!')
                    return redirect('store:register')

        else:
            form = RegisterForm()

            return render(request, 'register.html', {'form': form})

    elif request.method == 'GET':
        form = RegisterForm()

        return render(request, 'register.html', {'form': form})

templates/addtocart.html
{% extends 'base_store.html' %}

{% block customcss %}
<style>
/* Show it's not fixed to the top */
body {
  min-height: 75rem;
}
</style>

{% endblock %}

{% block content %}

    <main role="main" class="container">
      <div class="jumbotron">
        <h1>Added {{ item_name }} to cart...</h1>
          <img src="{{ image }}" alt="..." class="img-thumbnail">
        <p class="lead">You have added {{ item_qty }} of {{ item_name }} to your cart.</p>
        <a class="btn btn-lg btn-primary" href="{% url 'store:cart' %}" role="button">Continue to cart &raquo;</a>
      </div>
    </main>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
      <title>{{ page_title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
      {% block customcss %}
    {%  endblock %}
  </head>

  {% block content %}
  {%  endblock %}

</html>

templates/base_store.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
      <title>{{ page_title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <style>
        .no-margin {
            margin-bottom: 0px;
        }
    </style>

    <!-- Custom styles for this template -->
      {% block customcss %}
    {%  endblock %}
  </head>
 <body>

    <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #6B8E23;">
      <a class="navbar-brand" href="#">Plant A Tree</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'store:index' %}">Home <span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:showalltrees' %}">Trees</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'store:showallproducts' %}">Products</a>
          </li>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'store:wishlist' %}">Wishlist</a>
          </li>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'store:cart' %}">Cart</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0" method="get" action="{% url 'store:search' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search", name="words">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

   {% block content %}
  {%  endblock %}


     <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
 </body>
</html>

templates/cart.html
{% extends 'base_store.html' %}

{% block customcss %}
<style>
/* Show it's not fixed to the top */
body {
  min-height: 75rem;
}
</style>

{% endblock %}

{% block content %}

    <div class="container">

    <div class="row">
        <h2>Cart</h2>
    </div>

    {% if trees or products %}
         <table class="table table-striped">
                <thead>
                  <tr>
                      <th scope="col">Name</th>
                      <th scope="col">Qty</th>
                      <th scope="col">Increase Qty</th>
                      <th scope="col">Decrease Qty</th>
                      <th scope="col">Remove</th>
                  </tr>
                </thead>
                <tbody>
                {% for tree in trees %}
                  <tr>
                    <th scope="row">{{ tree.tree.name }}</th>
                    <td>{{ tree.qty }}</td>
                    <td><a href="{% url 'store:increase_tree_qty' item_id=tree.id  %}">Increase</a></td>
                    <td><a href="{% url 'store:decrease_tree_qty' item_id=tree.id %}">Decrease</a></td>
                      <td><a href="{% url 'store:remove_tree' item_id=tree.id %}">Remove</a></td>
                  </tr>
                {% endfor %}
                {% for product in products %}
                    <tr>
                    <th scope="row">{{ product.product.name }}</th>
                    <td>{{ product.qty }}</td>
                    <td><a href="{% url 'store:increase_product_qty' item_id=product.id  %}">Increase</a></td>
                    <td><a href="{% url 'store:decrease_product_qty' item_id=product.id %}">Decrease</a></td>
                      <td><a href="{% url 'store:remove_product' item_id=product.id %}">Remove</a></td>
                  </tr>
                {% endfor %}
                </tbody>
            </table>

                <a class="btn btn-lg btn-primary" href="{% url 'store:checkout' %}" role="button">Continue to checkout &raquo;</a>

    {% else %}
        <p>You don't have anything in your cart. Trying adding some stuff.</p>
    {% endif %}

    </div>

{% endblock %}

templates/product.html
{% extends 'base_store.html' %}

{%  block customcss %}
<style>
.carousel {
  margin-bottom: 4rem;
}

.carousel-caption {
  bottom: 3rem;
  z-index: 10;
}

.carousel-item {
  height: 32rem;
  background-color: #777;
}

.carousel-item > img {
  position: absolute;
  top: 0;
  left: 0;
  min-width: 100%;
  height: 32rem;
    max-width: none;
    object-fit:contain;
}
</style>

{%  endblock %}

{%  block content %}

    <main role="main">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="{{ product.image }}" alt="First slide">
            <div class="container">
            </div>
          </div>
      </div>
    </div>
    </main>

    <div class="container">
    <div class="row">
        <div class="col">
            <h2>{{ product.name }}</h2>
            <p>{{ product.description }}</p>
            <p>Category: {{ product.category }}</p>
            <p>Price: ${{ product.price }}</p>
        </div>
        <div class="col">
            <a class="btn btn-lg btn-success" href="{% url 'store:addproducttocart' item_id=product.id qty=1 %}" role="button">Add to cart &raquo;</a>
            <a class="btn btn-lg btn-primary" href="{% url 'store:addproducttowishlist' item_id=product.id %}" role="button">Add to wishlist &raquo;</a>
        </div>
    </div>
    </div>

{% endblock %}

templates/tree.html
{% extends 'base_store.html' %}

{%  block customcss %}
<style>
.carousel {
  margin-bottom: 4rem;
}

.carousel-caption {
  bottom: 3rem;
  z-index: 10;
}

.carousel-item {
  height: 32rem;
  background-color: #777;
}

.carousel-item > img {
  position: absolute;
  top: 0;
  left: 0;
  min-width: 100%;
  height: 32rem;
    max-width: none;
    object-fit:contain;
}
</style>

{%  endblock %}

{%  block content %}

    <main role="main">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="{{ tree.year_one }}" alt="First slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Year One</h1>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="{{ tree.year_two }}" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Year Two</h1>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="{{ tree.year_three }}" alt="Third slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Year Three</h1>
              </div>
            </div>
          </div>
            <div class="carousel-item">
            <img class="fourth-slide" src="{{ tree.year_five }}" alt="Fourth slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Year Five</h1>
              </div>
            </div>
          </div>
            <div class="carousel-item">
            <img class="fifth-slide" src="{{ tree.year_ten }}" alt="Five slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Year Ten</h1>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </main>

    <div class="container">
    <div class="row">
        <div class="col">
            <h2>{{ tree.name }}</h2>
            <p>{{ tree.description }}</p>
            <p>Category: {{ tree.category }}</p>
            <p>Height: {{ tree.height }} m</p>
            <p>Maintenance: {{ tree.get_maintenance_display }}</p>
            <p>Growth: {{ tree.get_growth_rate_display }}</p>
            <p>Fact: {{ tree.fun_facts }}</p>
        </div>
        <div class="col">
            <a class="btn btn-lg btn-success" href="{% url 'store:addtreetocart' item_id=tree.id qty=1 %}" role="button">Add to cart &raquo;</a>
                        <a class="btn btn-lg btn-primary" href="{% url 'store:addtreetowishlist' item_id=tree.id %}" role="button">Add to wishlist &raquo;</a>
        </div>
    </div>
    </div>

{% endblock %}

templates/wishlist.html
{% extends 'base_store.html' %}

{% block customcss %}
<style>
/* Show it's not fixed to the top */
body {
  min-height: 75rem;
}
</style>

{% endblock %}

{% block content %}

    <div class="container">

    <div class="row">
        <h2>Wishlist</h2>
    </div>

    {% if trees or products %}
         <table class="table table-striped">
                <thead>
                  <tr>
                      <th scope="col">Name</th>
                      <th scope="col">Add to Cart</th>
                      <th scope="col">Remove</th>
                  </tr>
                </thead>
                <tbody>
                {% for tree in trees %}
                  <tr>
                    <th scope="row">{{ tree.tree.name }}</th>
                    <td><a href="{% url 'store:addtreetocart' item_id=tree.tree.id qty=1 %}">Add to Cart</a></td>
                      <td><a href="{% url 'store:removetreefromwishlist' item_id=tree.tree.id %}">Remove</a></td>
                  </tr>
                {% endfor %}
                {% for product in products %}
                    <tr>
                    <th scope="row">{{ product.product.name }}</th>
                    <td><a href="{% url 'store:addproducttocart' item_id=product.product.id  qty=1 %}">Add to cart</a></td>
                      <td><a href="{% url 'store:removeproductfromwishlist' item_id=product.product.id %}">Remove</a></td>
                  </tr>
                {% endfor %}
                </tbody>
            </table>
    {% else %}
        <p>You don't have anything in your wishlist. Trying adding some stuff.</p>
    {% endif %}
    </div>

{% endblock %}